from globalvals import CMAX

"""
Color defs that I like.
"""

COLOR_RED = (CMAX, 0, CMAX/4)
COLOR_GREEN = (0, CMAX, CMAX/3.2)
COLOR_BLUE = (CMAX/4, CMAX, CMAX)

COLOR_YELLOW = (CMAX, CMAX, 0)
COLOR_ORANGE = (CMAX, CMAX, CMAX/3) # MEH!

COLOR_COOL_PINK = (CMAX/2, 0, CMAX)
COLOR_WARM_PINK = (CMAX, 0, CMAX/3)
COLOR_PINK = COLOR_WARM_PINK
COLOR_PURPLE = (CMAX/3, 0, CMAX)

COLOR_WHITE = (CMAX/2, CMAX, CMAX/2.2)
#COLOR_WHITE = (CMAX/3, CMAX, CMAX/2)

